accelerator: null
accumulate_grad_batches: 1
amp_backend: native
amp_level: O2
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
batch_size: 500
benchmark: false
check_val_every_n_epoch: 1
checkpoint_callback: true
data_path: !!python/object/apply:pathlib.PosixPath
- data
- traffic_noga_tilFAF_train.pkl
default_root_dir: null
deterministic: false
devices: null
distributed_backend: null
dropout: 0.0
early_stop: null
encoding_dim: 64
fast_dev_run: false
features:
- track
- groundspeed
- altitude
- timedelta
fix_prior: true
flush_logs_every_n_steps: 100
gpus: null
gradient_clip_algorithm: norm
gradient_clip_val: 0.5
h_dims:
- 216
- 128
- 64
info_features:
- latitude
- longitude
info_index: -1
ipus: null
kld_coef: 1.0
limit_predict_batches: 1.0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
llv_coef: 1.0
log_every_n_steps: 50
log_gpu_memory: null
logger: true
lr: 0.001
lr_gamma: 0.5
lr_step_size: 200
max_epochs: null
max_steps: null
max_time: null
min_epochs: null
min_steps: null
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
n_components: 1
network_name: fcvae
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 2
overfit_batches: 0.0
plugins: null
precision: 32
prepare_data_per_node: true
process_position: 0
profiler: null
progress_bar_refresh_rate: null
reg_pseudo: false
reload_dataloaders_every_epoch: false
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
resume_from_checkpoint: null
scale: 1.0
stochastic_weight_avg: false
sync_batchnorm: false
terminate_on_nan: false
test_batch_size: null
tpu_cores: null
track_grad_norm: -1
train_ratio: 0.8
truncated_bptt_steps: null
val_check_interval: 1.0
val_ratio: 0.2
weights_save_path: null
weights_summary: top
